version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - '1337:1337'
    volumes:
      - ./app:/srv/app
    depends_on:
      - db

  db:
    container_name: sqlite
    image: strapi/strapi
    restart: always
    volumes:
      - ./db:/var/lib/sqlite/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
